// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocket/domain/pb/user.proto

package com.rpg.rocket.domain;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // required string username = 2;
    /**
     * <code>required string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // optional string password = 3;
    /**
     * <code>optional string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional .rocket.domain.pb.User.Coordinate coordinate = 4;
    /**
     * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
     */
    boolean hasCoordinate();
    /**
     * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
     */
    com.rpg.rocket.domain.UserProtos.User.Coordinate getCoordinate();
    /**
     * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
     */
    com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder getCoordinateOrBuilder();
  }
  /**
   * Protobuf type {@code rocket.domain.pb.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              username_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
            case 34: {
              com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = coordinate_.toBuilder();
              }
              coordinate_ = input.readMessage(com.rpg.rocket.domain.UserProtos.User.Coordinate.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coordinate_);
                coordinate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpg.rocket.domain.UserProtos.User.class, com.rpg.rocket.domain.UserProtos.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public interface CoordinateOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required float x = 1;
      /**
       * <code>required float x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required float x = 1;</code>
       */
      float getX();

      // required float y = 2;
      /**
       * <code>required float y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required float y = 2;</code>
       */
      float getY();
    }
    /**
     * Protobuf type {@code rocket.domain.pb.User.Coordinate}
     */
    public static final class Coordinate extends
        com.google.protobuf.GeneratedMessage
        implements CoordinateOrBuilder {
      // Use Coordinate.newBuilder() to construct.
      private Coordinate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Coordinate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Coordinate defaultInstance;
      public static Coordinate getDefaultInstance() {
        return defaultInstance;
      }

      public Coordinate getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Coordinate(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 13: {
                bitField0_ |= 0x00000001;
                x_ = input.readFloat();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                y_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_Coordinate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rpg.rocket.domain.UserProtos.User.Coordinate.class, com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder.class);
      }

      public static com.google.protobuf.Parser<Coordinate> PARSER =
          new com.google.protobuf.AbstractParser<Coordinate>() {
        public Coordinate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Coordinate(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Coordinate> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required float x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private float x_;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }

      // required float y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private float y_;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }

      private void initFields() {
        x_ = 0F;
        y_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeFloat(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, y_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, y_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.rpg.rocket.domain.UserProtos.User.Coordinate parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.rpg.rocket.domain.UserProtos.User.Coordinate prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code rocket.domain.pb.User.Coordinate}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_Coordinate_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_Coordinate_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.rpg.rocket.domain.UserProtos.User.Coordinate.class, com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder.class);
        }

        // Construct using com.rpg.rocket.domain.UserProtos.User.Coordinate.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          x_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_Coordinate_descriptor;
        }

        public com.rpg.rocket.domain.UserProtos.User.Coordinate getDefaultInstanceForType() {
          return com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance();
        }

        public com.rpg.rocket.domain.UserProtos.User.Coordinate build() {
          com.rpg.rocket.domain.UserProtos.User.Coordinate result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.rpg.rocket.domain.UserProtos.User.Coordinate buildPartial() {
          com.rpg.rocket.domain.UserProtos.User.Coordinate result = new com.rpg.rocket.domain.UserProtos.User.Coordinate(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.rpg.rocket.domain.UserProtos.User.Coordinate) {
            return mergeFrom((com.rpg.rocket.domain.UserProtos.User.Coordinate)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.rpg.rocket.domain.UserProtos.User.Coordinate other) {
          if (other == com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.rpg.rocket.domain.UserProtos.User.Coordinate parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.rpg.rocket.domain.UserProtos.User.Coordinate) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required float x = 1;
        private float x_ ;
        /**
         * <code>required float x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required float x = 1;</code>
         */
        public float getX() {
          return x_;
        }
        /**
         * <code>required float x = 1;</code>
         */
        public Builder setX(float value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0F;
          onChanged();
          return this;
        }

        // required float y = 2;
        private float y_ ;
        /**
         * <code>required float y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required float y = 2;</code>
         */
        public float getY() {
          return y_;
        }
        /**
         * <code>required float y = 2;</code>
         */
        public Builder setY(float value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:rocket.domain.pb.User.Coordinate)
      }

      static {
        defaultInstance = new Coordinate(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:rocket.domain.pb.User.Coordinate)
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // required string username = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object username_;
    /**
     * <code>required string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .rocket.domain.pb.User.Coordinate coordinate = 4;
    public static final int COORDINATE_FIELD_NUMBER = 4;
    private com.rpg.rocket.domain.UserProtos.User.Coordinate coordinate_;
    /**
     * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
     */
    public boolean hasCoordinate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
     */
    public com.rpg.rocket.domain.UserProtos.User.Coordinate getCoordinate() {
      return coordinate_;
    }
    /**
     * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
     */
    public com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder getCoordinateOrBuilder() {
      return coordinate_;
    }

    private void initFields() {
      id_ = 0L;
      username_ = "";
      password_ = "";
      coordinate_ = com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasCoordinate()) {
        if (!getCoordinate().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, coordinate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, coordinate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rpg.rocket.domain.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rpg.rocket.domain.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rpg.rocket.domain.UserProtos.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rocket.domain.pb.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rpg.rocket.domain.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rpg.rocket.domain.UserProtos.User.class, com.rpg.rocket.domain.UserProtos.User.Builder.class);
      }

      // Construct using com.rpg.rocket.domain.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoordinateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (coordinateBuilder_ == null) {
          coordinate_ = com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance();
        } else {
          coordinateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rpg.rocket.domain.UserProtos.internal_static_rocket_domain_pb_User_descriptor;
      }

      public com.rpg.rocket.domain.UserProtos.User getDefaultInstanceForType() {
        return com.rpg.rocket.domain.UserProtos.User.getDefaultInstance();
      }

      public com.rpg.rocket.domain.UserProtos.User build() {
        com.rpg.rocket.domain.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rpg.rocket.domain.UserProtos.User buildPartial() {
        com.rpg.rocket.domain.UserProtos.User result = new com.rpg.rocket.domain.UserProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (coordinateBuilder_ == null) {
          result.coordinate_ = coordinate_;
        } else {
          result.coordinate_ = coordinateBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rpg.rocket.domain.UserProtos.User) {
          return mergeFrom((com.rpg.rocket.domain.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rpg.rocket.domain.UserProtos.User other) {
        if (other == com.rpg.rocket.domain.UserProtos.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasCoordinate()) {
          mergeCoordinate(other.getCoordinate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasUsername()) {
          
          return false;
        }
        if (hasCoordinate()) {
          if (!getCoordinate().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rpg.rocket.domain.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rpg.rocket.domain.UserProtos.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required string username = 2;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      // optional string password = 3;
      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      // optional .rocket.domain.pb.User.Coordinate coordinate = 4;
      private com.rpg.rocket.domain.UserProtos.User.Coordinate coordinate_ = com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.rpg.rocket.domain.UserProtos.User.Coordinate, com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder, com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder> coordinateBuilder_;
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public boolean hasCoordinate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public com.rpg.rocket.domain.UserProtos.User.Coordinate getCoordinate() {
        if (coordinateBuilder_ == null) {
          return coordinate_;
        } else {
          return coordinateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public Builder setCoordinate(com.rpg.rocket.domain.UserProtos.User.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coordinate_ = value;
          onChanged();
        } else {
          coordinateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public Builder setCoordinate(
          com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder builderForValue) {
        if (coordinateBuilder_ == null) {
          coordinate_ = builderForValue.build();
          onChanged();
        } else {
          coordinateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public Builder mergeCoordinate(com.rpg.rocket.domain.UserProtos.User.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              coordinate_ != com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance()) {
            coordinate_ =
              com.rpg.rocket.domain.UserProtos.User.Coordinate.newBuilder(coordinate_).mergeFrom(value).buildPartial();
          } else {
            coordinate_ = value;
          }
          onChanged();
        } else {
          coordinateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public Builder clearCoordinate() {
        if (coordinateBuilder_ == null) {
          coordinate_ = com.rpg.rocket.domain.UserProtos.User.Coordinate.getDefaultInstance();
          onChanged();
        } else {
          coordinateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder getCoordinateBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getCoordinateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      public com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder getCoordinateOrBuilder() {
        if (coordinateBuilder_ != null) {
          return coordinateBuilder_.getMessageOrBuilder();
        } else {
          return coordinate_;
        }
      }
      /**
       * <code>optional .rocket.domain.pb.User.Coordinate coordinate = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.rpg.rocket.domain.UserProtos.User.Coordinate, com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder, com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder> 
          getCoordinateFieldBuilder() {
        if (coordinateBuilder_ == null) {
          coordinateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.rpg.rocket.domain.UserProtos.User.Coordinate, com.rpg.rocket.domain.UserProtos.User.Coordinate.Builder, com.rpg.rocket.domain.UserProtos.User.CoordinateOrBuilder>(
                  coordinate_,
                  getParentForChildren(),
                  isClean());
          coordinate_ = null;
        }
        return coordinateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:rocket.domain.pb.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rocket.domain.pb.User)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rocket_domain_pb_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rocket_domain_pb_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rocket_domain_pb_User_Coordinate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rocket_domain_pb_User_Coordinate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033rocket/domain/pb/user.proto\022\020rocket.do" +
      "main.pb\"\221\001\n\004User\022\n\n\002id\030\001 \002(\003\022\020\n\010username" +
      "\030\002 \002(\t\022\020\n\010password\030\003 \001(\t\0225\n\ncoordinate\030\004" +
      " \001(\0132!.rocket.domain.pb.User.Coordinate\032" +
      "\"\n\nCoordinate\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002B#\n\025c" +
      "om.rpg.rocket.domainB\nUserProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rocket_domain_pb_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rocket_domain_pb_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rocket_domain_pb_User_descriptor,
              new java.lang.String[] { "Id", "Username", "Password", "Coordinate", });
          internal_static_rocket_domain_pb_User_Coordinate_descriptor =
            internal_static_rocket_domain_pb_User_descriptor.getNestedTypes().get(0);
          internal_static_rocket_domain_pb_User_Coordinate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rocket_domain_pb_User_Coordinate_descriptor,
              new java.lang.String[] { "X", "Y", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
